# GoReleaser configuration for web2mail
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    binary: web2mail
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: web2mail
    package_name: web2mail
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    maintainer: Faisal <faisal@example.com>
    description: A professional bridge to relay webhooks to SMTP/Sendmail
    license: MIT
    formats:
      - deb
    contents:
      - src: ./web2mail
        dst: /usr/bin/web2mail

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
