#!/bin/bash

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost
if yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

# Remove systemd service
ynh_config_remove_systemd

# Remove nginx config
ynh_config_remove_nginx

# Remove logrotate config
ynh_remove_logrotate

# Remove logs
ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
